
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - bert
skip_tags: true

version: 1.0.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

cache:
- packages

build_cloud: Docker
image: Linux

install:
- # mozroots --import --machine --sync
- apt-get install -y certmgr 
- certmgr -ssl -m https://go.microsoft.com
- certmgr -ssl -m https://nugetgallery.blob.core.windows.net
- certmgr -ssl -m https://nuget.org
- DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
- ln -sf /usr/share/zoneinfo/CEST /etc/localtime
- DEBIAN_FRONTEND=noninteractive apt-get install -y nuget

before_build:
- nuget restore
  
build_script:
- msbuild BB74.Controls\BB74.Xwt.Controls.csproj /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:ProjectReferences=false /p:TargetFrameworkVersion=v4.0;Configuration=Release;Platform="Any CPU"
- mkdir nuget
- nuget pack BB74.Controls\BB74.Xwt.Controls.csproj -Properties:"Configuration=Release;Platform=AnyCPU"-Symbols -OutputDirectory nuget
- dir nuget

artifacts:
- path: nuget\*.nupkg

test:  off
deploy: off
...
